.PHONY: setup clean status test capture

setup:
	@echo "a" | sudo -S ./setup.sh setup

clean:
	@echo "a" | sudo -S ./setup.sh clean

status:
	@echo "a" | sudo -S ./setup.sh status

test:
	@echo "a" | sudo -S ./setup.sh test

capture:
	@echo "a" | sudo -S ./setup.sh capture
