/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mount3.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_mountproc3_null_3 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (mountproc3_null_3_svc(result, rqstp));
}

int
_mountproc3_mnt_3 (dirpath  *argp, void *result, struct svc_req *rqstp)
{
	return (mountproc3_mnt_3_svc(*argp, result, rqstp));
}

int
_mountproc3_umnt_3 (dirpath  *argp, void *result, struct svc_req *rqstp)
{
	return (mountproc3_umnt_3_svc(*argp, result, rqstp));
}

void
mountprog_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		dirpath mountproc3_mnt_3_arg;
		dirpath mountproc3_umnt_3_arg;
	} argument;
	union {
		mountres3 mountproc3_mnt_3_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case MOUNTPROC3_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mountproc3_null_3;
		break;

	case MOUNTPROC3_MNT:
		_xdr_argument = (xdrproc_t) xdr_dirpath;
		_xdr_result = (xdrproc_t) xdr_mountres3;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mountproc3_mnt_3;
		break;

	case MOUNTPROC3_UMNT:
		_xdr_argument = (xdrproc_t) xdr_dirpath;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mountproc3_umnt_3;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!mountprog_3_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
