/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MOUNT3_H_RPCGEN
#define _MOUNT3_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define FHSIZE3 64
#define MNTPATHLEN 1024
#define MNTNAMLEN 255

typedef char *dirpath;

typedef struct {
	u_int fhandle3_len;
	char *fhandle3_val;
} fhandle3;

enum mountstat3 {
	MNT3_OK = 0,
	MNT3ERR_PERM = 1,
	MNT3ERR_NOENT = 2,
	MNT3ERR_IO = 5,
	MNT3ERR_ACCES = 13,
	MNT3ERR_NOTDIR = 20,
	MNT3ERR_INVAL = 22,
	MNT3ERR_NAMETOOLONG = 63,
	MNT3ERR_NOTSUPP = 10004,
	MNT3ERR_SERVERFAULT = 10006,
};
typedef enum mountstat3 mountstat3;

struct mountres3_ok {
	fhandle3 fhandle;
	struct {
		u_int auth_flavors_len;
		int *auth_flavors_val;
	} auth_flavors;
};
typedef struct mountres3_ok mountres3_ok;

struct mountres3 {
	mountstat3 fhs_status;
	union {
		mountres3_ok mountinfo;
	} mountres3_u;
};
typedef struct mountres3 mountres3;

#define MOUNTPROG 100005
#define MOUNTVERS3 3

#if defined(__STDC__) || defined(__cplusplus)
#define MOUNTPROC3_NULL 0
extern  enum clnt_stat mountproc3_null_3(void *, CLIENT *);
extern  bool_t mountproc3_null_3_svc(void *, struct svc_req *);
#define MOUNTPROC3_MNT 1
extern  enum clnt_stat mountproc3_mnt_3(dirpath , mountres3 *, CLIENT *);
extern  bool_t mountproc3_mnt_3_svc(dirpath , mountres3 *, struct svc_req *);
#define MOUNTPROC3_UMNT 3
extern  enum clnt_stat mountproc3_umnt_3(dirpath , void *, CLIENT *);
extern  bool_t mountproc3_umnt_3_svc(dirpath , void *, struct svc_req *);
extern int mountprog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MOUNTPROC3_NULL 0
extern  enum clnt_stat mountproc3_null_3();
extern  bool_t mountproc3_null_3_svc();
#define MOUNTPROC3_MNT 1
extern  enum clnt_stat mountproc3_mnt_3();
extern  bool_t mountproc3_mnt_3_svc();
#define MOUNTPROC3_UMNT 3
extern  enum clnt_stat mountproc3_umnt_3();
extern  bool_t mountproc3_umnt_3_svc();
extern int mountprog_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dirpath (XDR *, dirpath*);
extern  bool_t xdr_fhandle3 (XDR *, fhandle3*);
extern  bool_t xdr_mountstat3 (XDR *, mountstat3*);
extern  bool_t xdr_mountres3_ok (XDR *, mountres3_ok*);
extern  bool_t xdr_mountres3 (XDR *, mountres3*);

#else /* K&R C */
extern bool_t xdr_dirpath ();
extern bool_t xdr_fhandle3 ();
extern bool_t xdr_mountstat3 ();
extern bool_t xdr_mountres3_ok ();
extern bool_t xdr_mountres3 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MOUNT3_H_RPCGEN */
