/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NFS3_H_RPCGEN
#define _NFS3_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#define NFS3_FHSIZE 64
#define NFS3_COOKIEVERFSIZE 8
#define NFS3_CREATEVERFSIZE 8
#define NFS3_WRITEVERFSIZE 8
#define NFS3_MAXDATA 1048576
#define NFS3_MAXNAMLEN 255
#define NFS3_MAXPATHLEN 1024

typedef u_quad_t uint64;

typedef quad_t int64;

typedef u_int uint32;

typedef int int32;

typedef char *filename3;

typedef uint64 cookie3;

typedef char cookieverf3[NFS3_COOKIEVERFSIZE];

struct nfs_fh3 {
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct nfs_fh3 nfs_fh3;

enum nfsstat3 {
	NFS3_OK = 0,
	NFS3ERR_PERM = 1,
	NFS3ERR_NOENT = 2,
	NFS3ERR_IO = 5,
	NFS3ERR_NXIO = 6,
	NFS3ERR_ACCES = 13,
	NFS3ERR_EXIST = 17,
	NFS3ERR_XDEV = 18,
	NFS3ERR_NODEV = 19,
	NFS3ERR_NOTDIR = 20,
	NFS3ERR_ISDIR = 21,
	NFS3ERR_INVAL = 22,
	NFS3ERR_FBIG = 27,
	NFS3ERR_NOSPC = 28,
	NFS3ERR_ROFS = 30,
	NFS3ERR_MLINK = 31,
	NFS3ERR_NAMETOOLONG = 63,
	NFS3ERR_NOTEMPTY = 66,
	NFS3ERR_DQUOT = 69,
	NFS3ERR_STALE = 70,
	NFS3ERR_REMOTE = 71,
	NFS3ERR_BADHANDLE = 10001,
	NFS3ERR_NOT_SYNC = 10002,
	NFS3ERR_BAD_COOKIE = 10003,
	NFS3ERR_NOTSUPP = 10004,
	NFS3ERR_TOOSMALL = 10005,
	NFS3ERR_SERVERFAULT = 10006,
	NFS3ERR_BADTYPE = 10007,
	NFS3ERR_JUKEBOX = 10008,
};
typedef enum nfsstat3 nfsstat3;

enum ftype3 {
	NF3REG = 1,
	NF3DIR = 2,
	NF3BLK = 3,
	NF3CHR = 4,
	NF3LNK = 5,
	NF3SOCK = 6,
	NF3FIFO = 7,
};
typedef enum ftype3 ftype3;

struct specdata3 {
	uint32 specdata1;
	uint32 specdata2;
};
typedef struct specdata3 specdata3;

struct nfstime3 {
	uint32 seconds;
	uint32 nseconds;
};
typedef struct nfstime3 nfstime3;

struct fattr3 {
	ftype3 type;
	uint32 mode;
	uint32 nlink;
	uint32 uid;
	uint32 gid;
	uint64 size;
	uint64 used;
	specdata3 rdev;
	uint64 fsid;
	uint64 fileid;
	nfstime3 atime;
	nfstime3 mtime;
	nfstime3 ctime;
};
typedef struct fattr3 fattr3;

struct post_op_attr {
	bool_t attributes_follow;
	union {
		fattr3 attributes;
	} post_op_attr_u;
};
typedef struct post_op_attr post_op_attr;

struct wcc_attr {
	uint64 size;
	nfstime3 mtime;
	nfstime3 ctime;
};
typedef struct wcc_attr wcc_attr;

struct pre_op_attr {
	bool_t attributes_follow;
	union {
		wcc_attr attributes;
	} pre_op_attr_u;
};
typedef struct pre_op_attr pre_op_attr;

struct wcc_data {
	pre_op_attr before;
	post_op_attr after;
};
typedef struct wcc_data wcc_data;

struct diropargs3 {
	nfs_fh3 dir;
	filename3 name;
};
typedef struct diropargs3 diropargs3;

struct GETATTR3args {
	nfs_fh3 object;
};
typedef struct GETATTR3args GETATTR3args;

struct GETATTR3res {
	nfsstat3 status;
	union {
		fattr3 attributes;
	} GETATTR3res_u;
};
typedef struct GETATTR3res GETATTR3res;

struct LOOKUP3args {
	diropargs3 what;
};
typedef struct LOOKUP3args LOOKUP3args;

struct LOOKUP3resok {
	nfs_fh3 object;
	post_op_attr obj_attributes;
	post_op_attr dir_attributes;
};
typedef struct LOOKUP3resok LOOKUP3resok;

struct LOOKUP3resfail {
	post_op_attr dir_attributes;
};
typedef struct LOOKUP3resfail LOOKUP3resfail;

struct LOOKUP3res {
	nfsstat3 status;
	union {
		LOOKUP3resok resok;
		LOOKUP3resfail resfail;
	} LOOKUP3res_u;
};
typedef struct LOOKUP3res LOOKUP3res;
#define ACCESS3_READ 0x0001
#define ACCESS3_LOOKUP 0x0002
#define ACCESS3_MODIFY 0x0004
#define ACCESS3_EXTEND 0x0008
#define ACCESS3_DELETE 0x0010
#define ACCESS3_EXECUTE 0x0020

struct ACCESS3args {
	nfs_fh3 object;
	uint32 access;
};
typedef struct ACCESS3args ACCESS3args;

struct ACCESS3resok {
	post_op_attr obj_attributes;
	uint32 access;
};
typedef struct ACCESS3resok ACCESS3resok;

struct ACCESS3resfail {
	post_op_attr obj_attributes;
};
typedef struct ACCESS3resfail ACCESS3resfail;

struct ACCESS3res {
	nfsstat3 status;
	union {
		ACCESS3resok resok;
		ACCESS3resfail resfail;
	} ACCESS3res_u;
};
typedef struct ACCESS3res ACCESS3res;

struct READ3args {
	nfs_fh3 file;
	uint64 offset;
	uint32 count;
};
typedef struct READ3args READ3args;

struct READ3resok {
	post_op_attr file_attributes;
	uint32 count;
	bool_t eof;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct READ3resok READ3resok;

struct READ3resfail {
	post_op_attr file_attributes;
};
typedef struct READ3resfail READ3resfail;

struct READ3res {
	nfsstat3 status;
	union {
		READ3resok resok;
		READ3resfail resfail;
	} READ3res_u;
};
typedef struct READ3res READ3res;

enum stable_how {
	UNSTABLE = 0,
	DATA_SYNC = 1,
	FILE_SYNC = 2,
};
typedef enum stable_how stable_how;

struct WRITE3args {
	nfs_fh3 file;
	uint64 offset;
	uint32 count;
	stable_how stable;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct WRITE3args WRITE3args;

struct WRITE3resok {
	wcc_data file_wcc;
	uint32 count;
	stable_how committed;
	char verf[NFS3_WRITEVERFSIZE];
};
typedef struct WRITE3resok WRITE3resok;

struct WRITE3resfail {
	wcc_data file_wcc;
};
typedef struct WRITE3resfail WRITE3resfail;

struct WRITE3res {
	nfsstat3 status;
	union {
		WRITE3resok resok;
		WRITE3resfail resfail;
	} WRITE3res_u;
};
typedef struct WRITE3res WRITE3res;

struct post_op_fh3 {
	bool_t handle_follows;
	union {
		nfs_fh3 handle;
	} post_op_fh3_u;
};
typedef struct post_op_fh3 post_op_fh3;

struct set_mode3 {
	bool_t set_it;
	union {
		uint32 mode;
	} set_mode3_u;
};
typedef struct set_mode3 set_mode3;

struct set_uid3 {
	bool_t set_it;
	union {
		uint32 uid;
	} set_uid3_u;
};
typedef struct set_uid3 set_uid3;

struct set_gid3 {
	bool_t set_it;
	union {
		uint32 gid;
	} set_gid3_u;
};
typedef struct set_gid3 set_gid3;

struct set_size3 {
	bool_t set_it;
	union {
		uint64 size;
	} set_size3_u;
};
typedef struct set_size3 set_size3;

enum time_how {
	DONT_CHANGE = 0,
	SET_TO_SERVER_TIME = 1,
	SET_TO_CLIENT_TIME = 2,
};
typedef enum time_how time_how;

struct set_atime {
	time_how set_it;
	union {
		nfstime3 atime;
	} set_atime_u;
};
typedef struct set_atime set_atime;

struct set_mtime {
	time_how set_it;
	union {
		nfstime3 mtime;
	} set_mtime_u;
};
typedef struct set_mtime set_mtime;

struct sattr3 {
	set_mode3 mode;
	set_uid3 uid;
	set_gid3 gid;
	set_size3 size;
	set_atime atime;
	set_mtime mtime;
};
typedef struct sattr3 sattr3;

struct sattrguard3 {
	bool_t check;
	union {
		nfstime3 obj_ctime;
	} sattrguard3_u;
};
typedef struct sattrguard3 sattrguard3;

struct SETATTR3args {
	nfs_fh3 object;
	sattr3 new_attributes;
	sattrguard3 guard;
};
typedef struct SETATTR3args SETATTR3args;

struct SETATTR3resok {
	wcc_data obj_wcc;
};
typedef struct SETATTR3resok SETATTR3resok;

struct SETATTR3resfail {
	wcc_data obj_wcc;
};
typedef struct SETATTR3resfail SETATTR3resfail;

struct SETATTR3res {
	nfsstat3 status;
	union {
		SETATTR3resok resok;
		SETATTR3resfail resfail;
	} SETATTR3res_u;
};
typedef struct SETATTR3res SETATTR3res;

enum createmode3 {
	UNCHECKED = 0,
	GUARDED = 1,
	EXCLUSIVE = 2,
};
typedef enum createmode3 createmode3;

typedef char createverf3[NFS3_CREATEVERFSIZE];

struct createhow3 {
	createmode3 mode;
	union {
		sattr3 obj_attributes;
		sattr3 g_obj_attributes;
		createverf3 verf;
	} createhow3_u;
};
typedef struct createhow3 createhow3;

struct CREATE3args {
	diropargs3 where;
	createhow3 how;
};
typedef struct CREATE3args CREATE3args;

struct CREATE3resok {
	post_op_fh3 obj;
	post_op_attr obj_attributes;
	wcc_data dir_wcc;
};
typedef struct CREATE3resok CREATE3resok;

struct CREATE3resfail {
	wcc_data dir_wcc;
};
typedef struct CREATE3resfail CREATE3resfail;

struct CREATE3res {
	nfsstat3 status;
	union {
		CREATE3resok resok;
		CREATE3resfail resfail;
	} CREATE3res_u;
};
typedef struct CREATE3res CREATE3res;

struct REMOVE3args {
	diropargs3 object;
};
typedef struct REMOVE3args REMOVE3args;

struct REMOVE3resok {
	wcc_data dir_wcc;
};
typedef struct REMOVE3resok REMOVE3resok;

struct REMOVE3resfail {
	wcc_data dir_wcc;
};
typedef struct REMOVE3resfail REMOVE3resfail;

struct REMOVE3res {
	nfsstat3 status;
	union {
		REMOVE3resok resok;
		REMOVE3resfail resfail;
	} REMOVE3res_u;
};
typedef struct REMOVE3res REMOVE3res;

struct entry3 {
	uint64 fileid;
	filename3 name;
	cookie3 cookie;
	struct entry3 *nextentry;
};
typedef struct entry3 entry3;

struct dirlist3 {
	entry3 *entries;
	bool_t eof;
};
typedef struct dirlist3 dirlist3;

struct READDIR3args {
	nfs_fh3 dir;
	cookie3 cookie;
	cookieverf3 cookieverf;
	uint32 count;
};
typedef struct READDIR3args READDIR3args;

struct READDIR3resok {
	post_op_attr dir_attributes;
	cookieverf3 cookieverf;
	dirlist3 reply;
};
typedef struct READDIR3resok READDIR3resok;

struct READDIR3resfail {
	post_op_attr dir_attributes;
};
typedef struct READDIR3resfail READDIR3resfail;

struct READDIR3res {
	nfsstat3 status;
	union {
		READDIR3resok resok;
		READDIR3resfail resfail;
	} READDIR3res_u;
};
typedef struct READDIR3res READDIR3res;

struct READDIRPLUS3args {
	nfs_fh3 dir;
	cookie3 cookie;
	cookieverf3 cookieverf;
	uint32 dircount;
	uint32 maxcount;
};
typedef struct READDIRPLUS3args READDIRPLUS3args;

struct READDIRPLUS3resfail {
	post_op_attr dir_attributes;
};
typedef struct READDIRPLUS3resfail READDIRPLUS3resfail;

struct READDIRPLUS3res {
	nfsstat3 status;
	union {
		READDIRPLUS3resfail resfail;
	} READDIRPLUS3res_u;
};
typedef struct READDIRPLUS3res READDIRPLUS3res;

struct FSINFO3args {
	nfs_fh3 fsroot;
};
typedef struct FSINFO3args FSINFO3args;

struct FSINFO3resok {
	post_op_attr obj_attributes;
	uint32 rtmax;
	uint32 rtpref;
	uint32 rtmult;
	uint32 wtmax;
	uint32 wtpref;
	uint32 wtmult;
	uint32 dtpref;
	uint64 maxfilesize;
	nfstime3 time_delta;
	uint32 properties;
};
typedef struct FSINFO3resok FSINFO3resok;

struct FSINFO3resfail {
	post_op_attr obj_attributes;
};
typedef struct FSINFO3resfail FSINFO3resfail;

struct FSINFO3res {
	nfsstat3 status;
	union {
		FSINFO3resok resok;
		FSINFO3resfail resfail;
	} FSINFO3res_u;
};
typedef struct FSINFO3res FSINFO3res;

struct DUMMY3args {
	nfs_fh3 object;
};
typedef struct DUMMY3args DUMMY3args;

struct DUMMY3res {
	nfsstat3 status;
};
typedef struct DUMMY3res DUMMY3res;

#define NFS_PROGRAM 100003
#define NFS_V3 3

#if defined(__STDC__) || defined(__cplusplus)
#define NFSPROC3_NULL 0
extern  enum clnt_stat nfsproc3_null_3(void *, CLIENT *);
extern  bool_t nfsproc3_null_3_svc(void *, struct svc_req *);
#define NFSPROC3_GETATTR 1
extern  enum clnt_stat nfsproc3_getattr_3(GETATTR3args , GETATTR3res *, CLIENT *);
extern  bool_t nfsproc3_getattr_3_svc(GETATTR3args , GETATTR3res *, struct svc_req *);
#define NFSPROC3_SETATTR 2
extern  enum clnt_stat nfsproc3_setattr_3(SETATTR3args , SETATTR3res *, CLIENT *);
extern  bool_t nfsproc3_setattr_3_svc(SETATTR3args , SETATTR3res *, struct svc_req *);
#define NFSPROC3_LOOKUP 3
extern  enum clnt_stat nfsproc3_lookup_3(LOOKUP3args , LOOKUP3res *, CLIENT *);
extern  bool_t nfsproc3_lookup_3_svc(LOOKUP3args , LOOKUP3res *, struct svc_req *);
#define NFSPROC3_ACCESS 4
extern  enum clnt_stat nfsproc3_access_3(ACCESS3args , ACCESS3res *, CLIENT *);
extern  bool_t nfsproc3_access_3_svc(ACCESS3args , ACCESS3res *, struct svc_req *);
#define NFSPROC3_READLINK 5
extern  enum clnt_stat nfsproc3_readlink_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_readlink_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_READ 6
extern  enum clnt_stat nfsproc3_read_3(READ3args , READ3res *, CLIENT *);
extern  bool_t nfsproc3_read_3_svc(READ3args , READ3res *, struct svc_req *);
#define NFSPROC3_WRITE 7
extern  enum clnt_stat nfsproc3_write_3(WRITE3args , WRITE3res *, CLIENT *);
extern  bool_t nfsproc3_write_3_svc(WRITE3args , WRITE3res *, struct svc_req *);
#define NFSPROC3_CREATE 8
extern  enum clnt_stat nfsproc3_create_3(CREATE3args , CREATE3res *, CLIENT *);
extern  bool_t nfsproc3_create_3_svc(CREATE3args , CREATE3res *, struct svc_req *);
#define NFSPROC3_MKDIR 9
extern  enum clnt_stat nfsproc3_mkdir_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_mkdir_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_SYMLINK 10
extern  enum clnt_stat nfsproc3_symlink_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_symlink_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_MKNOD 11
extern  enum clnt_stat nfsproc3_mknod_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_mknod_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_REMOVE 12
extern  enum clnt_stat nfsproc3_remove_3(REMOVE3args , REMOVE3res *, CLIENT *);
extern  bool_t nfsproc3_remove_3_svc(REMOVE3args , REMOVE3res *, struct svc_req *);
#define NFSPROC3_RMDIR 13
extern  enum clnt_stat nfsproc3_rmdir_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_rmdir_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_RENAME 14
extern  enum clnt_stat nfsproc3_rename_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_rename_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_LINK 15
extern  enum clnt_stat nfsproc3_link_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_link_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_READDIR 16
extern  enum clnt_stat nfsproc3_readdir_3(READDIR3args , READDIR3res *, CLIENT *);
extern  bool_t nfsproc3_readdir_3_svc(READDIR3args , READDIR3res *, struct svc_req *);
#define NFSPROC3_READDIRPLUS 17
extern  enum clnt_stat nfsproc3_readdirplus_3(READDIRPLUS3args , READDIRPLUS3res *, CLIENT *);
extern  bool_t nfsproc3_readdirplus_3_svc(READDIRPLUS3args , READDIRPLUS3res *, struct svc_req *);
#define NFSPROC3_FSINFO 19
extern  enum clnt_stat nfsproc3_fsinfo_3(FSINFO3args , FSINFO3res *, CLIENT *);
extern  bool_t nfsproc3_fsinfo_3_svc(FSINFO3args , FSINFO3res *, struct svc_req *);
#define NFSPROC3_FSSTAT 18
extern  enum clnt_stat nfsproc3_fsstat_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_fsstat_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_PATHCONF 20
extern  enum clnt_stat nfsproc3_pathconf_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_pathconf_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
#define NFSPROC3_COMMIT 21
extern  enum clnt_stat nfsproc3_commit_3(DUMMY3args , DUMMY3res *, CLIENT *);
extern  bool_t nfsproc3_commit_3_svc(DUMMY3args , DUMMY3res *, struct svc_req *);
extern int nfs_program_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NFSPROC3_NULL 0
extern  enum clnt_stat nfsproc3_null_3();
extern  bool_t nfsproc3_null_3_svc();
#define NFSPROC3_GETATTR 1
extern  enum clnt_stat nfsproc3_getattr_3();
extern  bool_t nfsproc3_getattr_3_svc();
#define NFSPROC3_SETATTR 2
extern  enum clnt_stat nfsproc3_setattr_3();
extern  bool_t nfsproc3_setattr_3_svc();
#define NFSPROC3_LOOKUP 3
extern  enum clnt_stat nfsproc3_lookup_3();
extern  bool_t nfsproc3_lookup_3_svc();
#define NFSPROC3_ACCESS 4
extern  enum clnt_stat nfsproc3_access_3();
extern  bool_t nfsproc3_access_3_svc();
#define NFSPROC3_READLINK 5
extern  enum clnt_stat nfsproc3_readlink_3();
extern  bool_t nfsproc3_readlink_3_svc();
#define NFSPROC3_READ 6
extern  enum clnt_stat nfsproc3_read_3();
extern  bool_t nfsproc3_read_3_svc();
#define NFSPROC3_WRITE 7
extern  enum clnt_stat nfsproc3_write_3();
extern  bool_t nfsproc3_write_3_svc();
#define NFSPROC3_CREATE 8
extern  enum clnt_stat nfsproc3_create_3();
extern  bool_t nfsproc3_create_3_svc();
#define NFSPROC3_MKDIR 9
extern  enum clnt_stat nfsproc3_mkdir_3();
extern  bool_t nfsproc3_mkdir_3_svc();
#define NFSPROC3_SYMLINK 10
extern  enum clnt_stat nfsproc3_symlink_3();
extern  bool_t nfsproc3_symlink_3_svc();
#define NFSPROC3_MKNOD 11
extern  enum clnt_stat nfsproc3_mknod_3();
extern  bool_t nfsproc3_mknod_3_svc();
#define NFSPROC3_REMOVE 12
extern  enum clnt_stat nfsproc3_remove_3();
extern  bool_t nfsproc3_remove_3_svc();
#define NFSPROC3_RMDIR 13
extern  enum clnt_stat nfsproc3_rmdir_3();
extern  bool_t nfsproc3_rmdir_3_svc();
#define NFSPROC3_RENAME 14
extern  enum clnt_stat nfsproc3_rename_3();
extern  bool_t nfsproc3_rename_3_svc();
#define NFSPROC3_LINK 15
extern  enum clnt_stat nfsproc3_link_3();
extern  bool_t nfsproc3_link_3_svc();
#define NFSPROC3_READDIR 16
extern  enum clnt_stat nfsproc3_readdir_3();
extern  bool_t nfsproc3_readdir_3_svc();
#define NFSPROC3_READDIRPLUS 17
extern  enum clnt_stat nfsproc3_readdirplus_3();
extern  bool_t nfsproc3_readdirplus_3_svc();
#define NFSPROC3_FSINFO 19
extern  enum clnt_stat nfsproc3_fsinfo_3();
extern  bool_t nfsproc3_fsinfo_3_svc();
#define NFSPROC3_FSSTAT 18
extern  enum clnt_stat nfsproc3_fsstat_3();
extern  bool_t nfsproc3_fsstat_3_svc();
#define NFSPROC3_PATHCONF 20
extern  enum clnt_stat nfsproc3_pathconf_3();
extern  bool_t nfsproc3_pathconf_3_svc();
#define NFSPROC3_COMMIT 21
extern  enum clnt_stat nfsproc3_commit_3();
extern  bool_t nfsproc3_commit_3_svc();
extern int nfs_program_3_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_uint64 (XDR *, uint64*);
extern  bool_t xdr_int64 (XDR *, int64*);
extern  bool_t xdr_uint32 (XDR *, uint32*);
extern  bool_t xdr_int32 (XDR *, int32*);
extern  bool_t xdr_filename3 (XDR *, filename3*);
extern  bool_t xdr_cookie3 (XDR *, cookie3*);
extern  bool_t xdr_cookieverf3 (XDR *, cookieverf3);
extern  bool_t xdr_nfs_fh3 (XDR *, nfs_fh3*);
extern  bool_t xdr_nfsstat3 (XDR *, nfsstat3*);
extern  bool_t xdr_ftype3 (XDR *, ftype3*);
extern  bool_t xdr_specdata3 (XDR *, specdata3*);
extern  bool_t xdr_nfstime3 (XDR *, nfstime3*);
extern  bool_t xdr_fattr3 (XDR *, fattr3*);
extern  bool_t xdr_post_op_attr (XDR *, post_op_attr*);
extern  bool_t xdr_wcc_attr (XDR *, wcc_attr*);
extern  bool_t xdr_pre_op_attr (XDR *, pre_op_attr*);
extern  bool_t xdr_wcc_data (XDR *, wcc_data*);
extern  bool_t xdr_diropargs3 (XDR *, diropargs3*);
extern  bool_t xdr_GETATTR3args (XDR *, GETATTR3args*);
extern  bool_t xdr_GETATTR3res (XDR *, GETATTR3res*);
extern  bool_t xdr_LOOKUP3args (XDR *, LOOKUP3args*);
extern  bool_t xdr_LOOKUP3resok (XDR *, LOOKUP3resok*);
extern  bool_t xdr_LOOKUP3resfail (XDR *, LOOKUP3resfail*);
extern  bool_t xdr_LOOKUP3res (XDR *, LOOKUP3res*);
extern  bool_t xdr_ACCESS3args (XDR *, ACCESS3args*);
extern  bool_t xdr_ACCESS3resok (XDR *, ACCESS3resok*);
extern  bool_t xdr_ACCESS3resfail (XDR *, ACCESS3resfail*);
extern  bool_t xdr_ACCESS3res (XDR *, ACCESS3res*);
extern  bool_t xdr_READ3args (XDR *, READ3args*);
extern  bool_t xdr_READ3resok (XDR *, READ3resok*);
extern  bool_t xdr_READ3resfail (XDR *, READ3resfail*);
extern  bool_t xdr_READ3res (XDR *, READ3res*);
extern  bool_t xdr_stable_how (XDR *, stable_how*);
extern  bool_t xdr_WRITE3args (XDR *, WRITE3args*);
extern  bool_t xdr_WRITE3resok (XDR *, WRITE3resok*);
extern  bool_t xdr_WRITE3resfail (XDR *, WRITE3resfail*);
extern  bool_t xdr_WRITE3res (XDR *, WRITE3res*);
extern  bool_t xdr_post_op_fh3 (XDR *, post_op_fh3*);
extern  bool_t xdr_set_mode3 (XDR *, set_mode3*);
extern  bool_t xdr_set_uid3 (XDR *, set_uid3*);
extern  bool_t xdr_set_gid3 (XDR *, set_gid3*);
extern  bool_t xdr_set_size3 (XDR *, set_size3*);
extern  bool_t xdr_time_how (XDR *, time_how*);
extern  bool_t xdr_set_atime (XDR *, set_atime*);
extern  bool_t xdr_set_mtime (XDR *, set_mtime*);
extern  bool_t xdr_sattr3 (XDR *, sattr3*);
extern  bool_t xdr_sattrguard3 (XDR *, sattrguard3*);
extern  bool_t xdr_SETATTR3args (XDR *, SETATTR3args*);
extern  bool_t xdr_SETATTR3resok (XDR *, SETATTR3resok*);
extern  bool_t xdr_SETATTR3resfail (XDR *, SETATTR3resfail*);
extern  bool_t xdr_SETATTR3res (XDR *, SETATTR3res*);
extern  bool_t xdr_createmode3 (XDR *, createmode3*);
extern  bool_t xdr_createverf3 (XDR *, createverf3);
extern  bool_t xdr_createhow3 (XDR *, createhow3*);
extern  bool_t xdr_CREATE3args (XDR *, CREATE3args*);
extern  bool_t xdr_CREATE3resok (XDR *, CREATE3resok*);
extern  bool_t xdr_CREATE3resfail (XDR *, CREATE3resfail*);
extern  bool_t xdr_CREATE3res (XDR *, CREATE3res*);
extern  bool_t xdr_REMOVE3args (XDR *, REMOVE3args*);
extern  bool_t xdr_REMOVE3resok (XDR *, REMOVE3resok*);
extern  bool_t xdr_REMOVE3resfail (XDR *, REMOVE3resfail*);
extern  bool_t xdr_REMOVE3res (XDR *, REMOVE3res*);
extern  bool_t xdr_entry3 (XDR *, entry3*);
extern  bool_t xdr_dirlist3 (XDR *, dirlist3*);
extern  bool_t xdr_READDIR3args (XDR *, READDIR3args*);
extern  bool_t xdr_READDIR3resok (XDR *, READDIR3resok*);
extern  bool_t xdr_READDIR3resfail (XDR *, READDIR3resfail*);
extern  bool_t xdr_READDIR3res (XDR *, READDIR3res*);
extern  bool_t xdr_READDIRPLUS3args (XDR *, READDIRPLUS3args*);
extern  bool_t xdr_READDIRPLUS3resfail (XDR *, READDIRPLUS3resfail*);
extern  bool_t xdr_READDIRPLUS3res (XDR *, READDIRPLUS3res*);
extern  bool_t xdr_FSINFO3args (XDR *, FSINFO3args*);
extern  bool_t xdr_FSINFO3resok (XDR *, FSINFO3resok*);
extern  bool_t xdr_FSINFO3resfail (XDR *, FSINFO3resfail*);
extern  bool_t xdr_FSINFO3res (XDR *, FSINFO3res*);
extern  bool_t xdr_DUMMY3args (XDR *, DUMMY3args*);
extern  bool_t xdr_DUMMY3res (XDR *, DUMMY3res*);

#else /* K&R C */
extern bool_t xdr_uint64 ();
extern bool_t xdr_int64 ();
extern bool_t xdr_uint32 ();
extern bool_t xdr_int32 ();
extern bool_t xdr_filename3 ();
extern bool_t xdr_cookie3 ();
extern bool_t xdr_cookieverf3 ();
extern bool_t xdr_nfs_fh3 ();
extern bool_t xdr_nfsstat3 ();
extern bool_t xdr_ftype3 ();
extern bool_t xdr_specdata3 ();
extern bool_t xdr_nfstime3 ();
extern bool_t xdr_fattr3 ();
extern bool_t xdr_post_op_attr ();
extern bool_t xdr_wcc_attr ();
extern bool_t xdr_pre_op_attr ();
extern bool_t xdr_wcc_data ();
extern bool_t xdr_diropargs3 ();
extern bool_t xdr_GETATTR3args ();
extern bool_t xdr_GETATTR3res ();
extern bool_t xdr_LOOKUP3args ();
extern bool_t xdr_LOOKUP3resok ();
extern bool_t xdr_LOOKUP3resfail ();
extern bool_t xdr_LOOKUP3res ();
extern bool_t xdr_ACCESS3args ();
extern bool_t xdr_ACCESS3resok ();
extern bool_t xdr_ACCESS3resfail ();
extern bool_t xdr_ACCESS3res ();
extern bool_t xdr_READ3args ();
extern bool_t xdr_READ3resok ();
extern bool_t xdr_READ3resfail ();
extern bool_t xdr_READ3res ();
extern bool_t xdr_stable_how ();
extern bool_t xdr_WRITE3args ();
extern bool_t xdr_WRITE3resok ();
extern bool_t xdr_WRITE3resfail ();
extern bool_t xdr_WRITE3res ();
extern bool_t xdr_post_op_fh3 ();
extern bool_t xdr_set_mode3 ();
extern bool_t xdr_set_uid3 ();
extern bool_t xdr_set_gid3 ();
extern bool_t xdr_set_size3 ();
extern bool_t xdr_time_how ();
extern bool_t xdr_set_atime ();
extern bool_t xdr_set_mtime ();
extern bool_t xdr_sattr3 ();
extern bool_t xdr_sattrguard3 ();
extern bool_t xdr_SETATTR3args ();
extern bool_t xdr_SETATTR3resok ();
extern bool_t xdr_SETATTR3resfail ();
extern bool_t xdr_SETATTR3res ();
extern bool_t xdr_createmode3 ();
extern bool_t xdr_createverf3 ();
extern bool_t xdr_createhow3 ();
extern bool_t xdr_CREATE3args ();
extern bool_t xdr_CREATE3resok ();
extern bool_t xdr_CREATE3resfail ();
extern bool_t xdr_CREATE3res ();
extern bool_t xdr_REMOVE3args ();
extern bool_t xdr_REMOVE3resok ();
extern bool_t xdr_REMOVE3resfail ();
extern bool_t xdr_REMOVE3res ();
extern bool_t xdr_entry3 ();
extern bool_t xdr_dirlist3 ();
extern bool_t xdr_READDIR3args ();
extern bool_t xdr_READDIR3resok ();
extern bool_t xdr_READDIR3resfail ();
extern bool_t xdr_READDIR3res ();
extern bool_t xdr_READDIRPLUS3args ();
extern bool_t xdr_READDIRPLUS3resfail ();
extern bool_t xdr_READDIRPLUS3res ();
extern bool_t xdr_FSINFO3args ();
extern bool_t xdr_FSINFO3resok ();
extern bool_t xdr_FSINFO3resfail ();
extern bool_t xdr_FSINFO3res ();
extern bool_t xdr_DUMMY3args ();
extern bool_t xdr_DUMMY3res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NFS3_H_RPCGEN */
