/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs3.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_nfsproc3_null_3 (void  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_null_3_svc(result, rqstp));
}

int
_nfsproc3_getattr_3 (GETATTR3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_getattr_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_setattr_3 (SETATTR3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_setattr_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_lookup_3 (LOOKUP3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_lookup_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_access_3 (ACCESS3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_access_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_readlink_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_readlink_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_read_3 (READ3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_read_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_write_3 (WRITE3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_write_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_create_3 (CREATE3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_create_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_mkdir_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_mkdir_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_symlink_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_symlink_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_mknod_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_mknod_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_remove_3 (REMOVE3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_remove_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_rmdir_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_rmdir_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_rename_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_rename_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_link_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_link_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_readdir_3 (READDIR3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_readdir_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_readdirplus_3 (READDIRPLUS3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_readdirplus_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_fsinfo_3 (FSINFO3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_fsinfo_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_fsstat_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_fsstat_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_pathconf_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_pathconf_3_svc(*argp, result, rqstp));
}

int
_nfsproc3_commit_3 (DUMMY3args  *argp, void *result, struct svc_req *rqstp)
{
	return (nfsproc3_commit_3_svc(*argp, result, rqstp));
}

void
nfs_program_3(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		GETATTR3args nfsproc3_getattr_3_arg;
		SETATTR3args nfsproc3_setattr_3_arg;
		LOOKUP3args nfsproc3_lookup_3_arg;
		ACCESS3args nfsproc3_access_3_arg;
		DUMMY3args nfsproc3_readlink_3_arg;
		READ3args nfsproc3_read_3_arg;
		WRITE3args nfsproc3_write_3_arg;
		CREATE3args nfsproc3_create_3_arg;
		DUMMY3args nfsproc3_mkdir_3_arg;
		DUMMY3args nfsproc3_symlink_3_arg;
		DUMMY3args nfsproc3_mknod_3_arg;
		REMOVE3args nfsproc3_remove_3_arg;
		DUMMY3args nfsproc3_rmdir_3_arg;
		DUMMY3args nfsproc3_rename_3_arg;
		DUMMY3args nfsproc3_link_3_arg;
		READDIR3args nfsproc3_readdir_3_arg;
		READDIRPLUS3args nfsproc3_readdirplus_3_arg;
		FSINFO3args nfsproc3_fsinfo_3_arg;
		DUMMY3args nfsproc3_fsstat_3_arg;
		DUMMY3args nfsproc3_pathconf_3_arg;
		DUMMY3args nfsproc3_commit_3_arg;
	} argument;
	union {
		GETATTR3res nfsproc3_getattr_3_res;
		SETATTR3res nfsproc3_setattr_3_res;
		LOOKUP3res nfsproc3_lookup_3_res;
		ACCESS3res nfsproc3_access_3_res;
		DUMMY3res nfsproc3_readlink_3_res;
		READ3res nfsproc3_read_3_res;
		WRITE3res nfsproc3_write_3_res;
		CREATE3res nfsproc3_create_3_res;
		DUMMY3res nfsproc3_mkdir_3_res;
		DUMMY3res nfsproc3_symlink_3_res;
		DUMMY3res nfsproc3_mknod_3_res;
		REMOVE3res nfsproc3_remove_3_res;
		DUMMY3res nfsproc3_rmdir_3_res;
		DUMMY3res nfsproc3_rename_3_res;
		DUMMY3res nfsproc3_link_3_res;
		READDIR3res nfsproc3_readdir_3_res;
		READDIRPLUS3res nfsproc3_readdirplus_3_res;
		FSINFO3res nfsproc3_fsinfo_3_res;
		DUMMY3res nfsproc3_fsstat_3_res;
		DUMMY3res nfsproc3_pathconf_3_res;
		DUMMY3res nfsproc3_commit_3_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NFSPROC3_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_null_3;
		break;

	case NFSPROC3_GETATTR:
		_xdr_argument = (xdrproc_t) xdr_GETATTR3args;
		_xdr_result = (xdrproc_t) xdr_GETATTR3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_getattr_3;
		break;

	case NFSPROC3_SETATTR:
		_xdr_argument = (xdrproc_t) xdr_SETATTR3args;
		_xdr_result = (xdrproc_t) xdr_SETATTR3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_setattr_3;
		break;

	case NFSPROC3_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_LOOKUP3args;
		_xdr_result = (xdrproc_t) xdr_LOOKUP3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_lookup_3;
		break;

	case NFSPROC3_ACCESS:
		_xdr_argument = (xdrproc_t) xdr_ACCESS3args;
		_xdr_result = (xdrproc_t) xdr_ACCESS3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_access_3;
		break;

	case NFSPROC3_READLINK:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_readlink_3;
		break;

	case NFSPROC3_READ:
		_xdr_argument = (xdrproc_t) xdr_READ3args;
		_xdr_result = (xdrproc_t) xdr_READ3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_read_3;
		break;

	case NFSPROC3_WRITE:
		_xdr_argument = (xdrproc_t) xdr_WRITE3args;
		_xdr_result = (xdrproc_t) xdr_WRITE3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_write_3;
		break;

	case NFSPROC3_CREATE:
		_xdr_argument = (xdrproc_t) xdr_CREATE3args;
		_xdr_result = (xdrproc_t) xdr_CREATE3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_create_3;
		break;

	case NFSPROC3_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_mkdir_3;
		break;

	case NFSPROC3_SYMLINK:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_symlink_3;
		break;

	case NFSPROC3_MKNOD:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_mknod_3;
		break;

	case NFSPROC3_REMOVE:
		_xdr_argument = (xdrproc_t) xdr_REMOVE3args;
		_xdr_result = (xdrproc_t) xdr_REMOVE3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_remove_3;
		break;

	case NFSPROC3_RMDIR:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_rmdir_3;
		break;

	case NFSPROC3_RENAME:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_rename_3;
		break;

	case NFSPROC3_LINK:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_link_3;
		break;

	case NFSPROC3_READDIR:
		_xdr_argument = (xdrproc_t) xdr_READDIR3args;
		_xdr_result = (xdrproc_t) xdr_READDIR3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_readdir_3;
		break;

	case NFSPROC3_READDIRPLUS:
		_xdr_argument = (xdrproc_t) xdr_READDIRPLUS3args;
		_xdr_result = (xdrproc_t) xdr_READDIRPLUS3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_readdirplus_3;
		break;

	case NFSPROC3_FSINFO:
		_xdr_argument = (xdrproc_t) xdr_FSINFO3args;
		_xdr_result = (xdrproc_t) xdr_FSINFO3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_fsinfo_3;
		break;

	case NFSPROC3_FSSTAT:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_fsstat_3;
		break;

	case NFSPROC3_PATHCONF:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_pathconf_3;
		break;

	case NFSPROC3_COMMIT:
		_xdr_argument = (xdrproc_t) xdr_DUMMY3args;
		_xdr_result = (xdrproc_t) xdr_DUMMY3res;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_nfsproc3_commit_3;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!nfs_program_3_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}
