[global]
time_based=1
runtime=1000
; gtod_reduce=1
ioengine=aio
; ioengine=aio
; ioengine=mmap
; ioengine=sync
iodepth=64
direct=1
; sync=sync
; sync=dsync
numjobs=1
; fadvise_hint=0
; write_hint=none
bs=4k

[trash]
rw=randwrite
; rw=randread
; filename=/dev/nvme2n1:/dev/nvme1n1:/dev/nvme0n1:/dev/nvme3n1:/dev/nvme4n1:/dev/nvme5n1:/dev/nvme6n1:/dev/nvme7n1:/dev/nvme8n1:/dev/nvme9n1
; filename=/dev/vda:/dev/vdb:/dev/vdc:/dev/vdd:/dev/vde:/dev/vdf:/dev/vdg:/dev/vdh:/dev/vdi:/dev/vdj:/dev/vdk:/dev/vdl
; filename=/dev/nvme2n1
; filename=/dev/nvme1n1
; filename=/dev/nvme0n1
; filename=/dev/etherd/e1.1
; filename=/dev/nullb0
; filename=/home/martins3/mnt/a.dump
; filename=/dev/dummy
filename=/dev/sda
; filename=/home/martins3/a.dump
; filename=/home/martins3/mnt/a.dump
; filename=/dev/nullb0
; size=8000M
; rate_iops=10000

; [trash]
; ioengine=sync
; iodepth=1
; direct=0
; size=30G
; rw=randwrite
; # filename=/home/martins3/hack/qemu.ram
; filename=/home/martins3//hack/tmp/a
; gtod_reduce=1
; gtod_cpu=9
; clocksource=clock_gettime
